### ISSUE TITLE
Ability to be able to peek at current items in queue

### ISSUE THREAD

**Issue by pbse** [mhassan1/mongodb-queue-up#11]
Hey,

Requesting to add ability to be able to peek at all the non deleted items in the queue. Currently the `inFlight` function returns the count, but there are needs to just be able to look at all the items in the queue (including ackd and non ackd).

**Comment by mhassan1** [comment]
Thanks for the feature request!

I see we already have `total`, `size`, `inFlight`, and `done`, all of which return counts. Which of those are we looking to peek at?

**Comment by pbse** [comment]
`total` returns all including deleted.
`size` returns all non deleted that have visibility before now
`inFlight` returns all current ack'd items
`done` returns all deleted.

I am looking for all non deleted items in queue (regardless of its visibility or ackd)
